### PR TITLE
Michael Chen - Assignment6

### PR DESCRIPTION
**Pull request by michen32**
"ERROR: Permission to DS219/spark-seprep.git denied to michen32."

### CODE REVIEW

**Comment by aakankshaduggal** [comment]
Good job @michen32 10/10

**Comment by aakankshaduggal** [comment]
But this PR has assignment 6 alongwith assignment7. cc @sallyom @umohnani8

**Comment by michen32** [comment]
To be 100% honest, I can't remember what I did for branching and PR... will this be an issue right now?

**Comment by sallyom** [comment]
@michen32 @aakankshaduggal I'll merge the assignment6 & assignment7 PRs tomorrow in class - I'll first show Michael how to best separate the files so the assignment6 files are with this PR and the assignment7 files are with #138 - here's what you'll need to do (we can do this in class if it's not clear)- since you've already opened the PR from your main branch, we'll stick with using your main branch for this PR:

```bash
git checkout main
git log (cp the sha from the commit below `87ed...`
git rebase -i <commit below 87ed>
with vim, delete the 3 lines with the 3 unwanted commits, then close vim
git push -f origin main
```
Note: the 2 files for assignment 7 live in another branch, `assignment-7-branch` - deleting those commits from this PR won't affect that branch.

**Comment by sallyom** [comment]
@aakanksha I'm merging this, it has the image for assignment 7 too.

**Pull request merged**
