### PR TITLE
Added Solution for Leetcode's 'Merge two sorted linked lists' problem. -Implemented a Python solution to merge two sorted linked lists into one sorted list. -Compared node values from both lists, attaching the smaller node to the merged list, and appended the remainder of the non-exhausted list. - Used a dummy node to simplify list construction and returned the merged list starting from dummy.next.

### PR DESCRIPTION
**Pull request by danieldoh2**

### CODE REVIEW

**Comment by umohnani8** [comment]
@danieldoh2 please add a bit more description to your commit. Take a look at the assignment for an example. Amend your commit and force push it again for full credit.

**Comment by danieldoh2** [comment]
@umohnani8 Thanks for the feedback. Please let me know if my current description works.

**Comment by umohnani8** [comment]
@danieldoh2 you have updated the title of the PR and not the commit message. You need to do `git commit --amend` and update the commit message there and then do a force push `git push -f`.

**Comment by danieldoh2** [comment]
Ah, my bad. I amended the commit and force pushed it. @umohnani8

**Pull request merged**
