### PR TITLE
final update assignment 3

### PR DESCRIPTION
**Pull request by mattfrysinger**

### CODE REVIEW

**Comment by umohnani8** [comment]
@mattfrysinger you have 2 commits, please either squash the commits or delete the commit you don't want.

**Comment by mattfrysinger** [comment]
> @mattfrysinger you have 2 commits, please either squash the commits or delete the commit you don't want.

Can I delete a commit using the UI? How?

**Comment by umohnani8** [comment]
I don't think there is a way to delete a commit, you will have to do it via the terminal.

**Comment by umohnani8** [comment]
Closing as the deadline has passed.

**Pull request closed without merging**
