### PR TITLE
Minkyung(Kate) KimAssignment4

### PR DESCRIPTION
**Pull request by kate1787**

### CODE REVIEW

**Comment by umohnani8** [comment]
@kate1787 the assignment requires you to have a descriptive commit message. Please look at the assignment for an example commit message and amend your commit here if you would like full credit.

**Comment by kate1787** [comment]
I have written down my commit message on the latest commit. Do I have to write a commit message to every each?

**Comment by umohnani8** [comment]
Ah okay, I see that now. Ideally you will have a commit message for each commit and usually just 1 commit per PR. But this is fine, I will merge it. LGTM

**Comment by kate1787** [comment]
thank you!

**Pull request merged**
